In [1]:
import pandas as pd
import numpy as np

In [2]:
places_data=pd.read_csv("Places_Pune_OneHotEncoded.csv")
restaurants_data=pd.read_csv("Restaurant_Data_Pune.csv")
hotels_data=pd.read_csv("cleaned_hotels.csv")

In [3]:
places_data

,Name,Latitude,Longitude,Rating,Place_ID,amusement_park,art_gallery,campground,car_rental,cemetery,...,park,place_of_worship,point_of_interest,real_estate_agency,shopping_mall,store,synagogue,tourist_attraction,travel_agency,zoo
0,Aga Khan Palace,18.552494,73.901456,4.3,ChIJGxtxaBfBwjsR9GnVR3SpG6w,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
1,Balaji Temple,18.504428,73.838277,4.3,ChIJU7O62vS_wjsRu0sy4pQg-m0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,0
2,Bedekar Ganpati Mandir,18.511552,73.817586,4.5,ChIJ170MkL2_wjsRNmTCxikgfys,0,0,0,0,0,...,0,1,1,0,0,0,0,1,0,0
3,Biradvadi Hill,18.773074,73.836855,4.1,ChIJ47eaW4e1wjsRYzRPxn-JKOw,0,0,0,0,0,...,0,0,1,0,0,0,0,1,0,0
4,Bird Valley Udyan,18.657029,73.800178,4.0,ChIJocDhrC64wjsRSkxI1v1RnEc,0,0,0,0,0,...,1,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Lighthouse Mall,18.483283,73.862483,3.9,NaN,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
94,Reliance Mall,18.508191,73.834674,4.0,NaN,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
95,Phoenix Mall of the Millennium Wakad,18.607035,73.755695,4.4,NaN,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
96,93 Avenue,18.514243,73.905644,4.2,NaN,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
97,City One Mall,18.639034,73.801892,4.0,NaN,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0

In [4]:
restaurants_data

,Restaurant_Name,Locality,Ratings_out_of_5,price,Price Level,Latitude,Longitude
0,AB's - Absolute Barbecues,Hinjawadi,4.9,700,2,18.592753,73.738215
1,Cafe Co2 Resto Lounge,Bhugaon,4.6,750,2,20.949366,79.937583
2,Paasha - JW Marriott Pune,Senapati Bapat Road,4.6,1250,3,19.012171,72.836082
3,I Amsterdam,Hinjawadi,4.3,700,2,18.592753,73.738215
4,FC Road Social,Shivaji Nagar,4.5,750,2,25.884554,86.039850
...,...,...,...,...,...,...,...
2823,The Davanageri Benne Dosa,Chinchwad,3.8,125,1,18.640355,73.791713
2824,Chaat Bazaar,Swargate,3.8,225,1,18.499685,73.856883
2825,Golden Palms,Nigdi,3.4,250,1,18.660767,73.777826
2826,E Hide Cafe,Viman Nagar,3.8,250,1,17.446757,78.483820
2827,Shree Chamunda Purohit Dining Hall,Hinjawadi,3.8,250,1,18.592753,73.738215

In [5]:
null_mask = hotels_data.isnull().any(axis=1)
null_rows = hotels_data[null_mask]

print(null_rows)

Empty DataFrame
Columns: [property_name, area_x, hotel_star_rating_x, mmt_review_score_x, Price_x, Longitude, Latitude]
Index: []

In [6]:
hotels_data

,property_name,area_x,hotel_star_rating_x,mmt_review_score_x,Price_x,Longitude,Latitude
0,Hotel Golden Dream,"pune solapur rd, uruli kanchan",1,3.0,781,73.949065,18.500988
1,Hotel Yashraj Inn,"Pune Nagar Highway,Wagholil",1,3.5,1177,73.975046,18.579636
2,Seandee Hospitality,Kalyani Nagar,2,3.0,1240,73.905681,18.545542
3,Hotel Royal Park,"Kasarwadi,Mumbai Pune Highway",3,4.0,2680,73.827668,18.602083
4,Hotel Dreamland Pune,pune-nashik road,1,4.4,1728,73.875806,18.528050
...,...,...,...,...,...,...,...
135,Hotel Shiv Inn,"Chinchwad,Pimpri,Pimpri-Chinchwad",1,2.9,1447,73.655509,18.727259
136,Courtyard by Marriott Pune Hinjewadi,"Hinjewadi,P4 Rajiv Gandhi",4,4.8,10089,73.747194,18.590991
137,Hotel Hindusthan International (HHI),"Viman Nagar,Koregaon Park,Kalyani Nagar",4,4.4,4125,73.914789,18.561381
138,Supreme World Service Apartment,Koregaon Park,1,3.5,4000,73.901070,18.539200
139,Hotel Bhagyashree,Hadapsar,1,3.4,2218,73.941679,18.496678

In [7]:
restaurants_data.isnull().values.any()

False

In [8]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

# Assuming you have three DataFrames: places_data, restaurants_data, and hotels_data

# Drop unnecessary columns for the matching process
places_features = places_data[['Longitude', 'Latitude']]
restaurants_features = restaurants_data[['Longitude', 'Latitude']]
hotels_features = hotels_data[['Longitude', 'Latitude']]

# Use Nearest Neighbors to find the nearest place for each restaurant/hotel
knn = NearestNeighbors(n_neighbors=3, metric='haversine')
knn.fit(places_features)

# Find the nearest place for each restaurant
distances_restaurants, indices_restaurants = knn.kneighbors(restaurants_features)

# Find the nearest place for each hotel
distances_hotels, indices_hotels = knn.kneighbors(hotels_features)

# Create a new column 'Nearest_Place_Index' to store the index of the nearest place
restaurants_data['Nearest_Place_Index'] = indices_restaurants.flatten()
hotels_data['Nearest_Place_Index'] = indices_hotels.flatten()

# Reset index before merging to avoid length mismatch issue
restaurants_data = restaurants_data.reset_index(drop=True)
hotels_data = hotels_data.reset_index(drop=True)

# Merge the 'places_data' DataFrame with 'restaurants_data' and 'hotels_data' based on the 'Nearest_Place_Index'
restaurants_data = pd.merge(restaurants_data, places_data, left_on='Nearest_Place_Index', right_index=True, suffixes=('_restaurant', '_place'))
hotels_data = pd.merge(hotels_data, places_data, left_on='Nearest_Place_Index', right_index=True, suffixes=('_hotel', '_place'))

# Now, 'restaurants_data' and 'hotels_data' should have additional columns from the nearest place in 'places_data'.

ValueError: Length of values (8484) does not match length of index (2828)

In [9]:
# Merge 'restaurants_data' and 'hotels_data' based on the 'Nearest_Place_Index'
merged_data = pd.merge(restaurants_data, hotels_data, left_on='Nearest_Place_Index', right_on='Nearest_Place_Index', suffixes=('_restaurant', '_hotel'))

# Merge the combined data with 'places_data' based on the 'Nearest_Place_Index'
final_data = pd.merge(merged_data, places_data, left_on='Nearest_Place_Index', right_index=True, suffixes=('_combined', '_place'))

# Drop unnecessary columns
final_data = final_data.drop(columns=['Nearest_Place_Index'])

# Save the final dataset to a new CSV file
final_data.to_csv('final_dataset.csv', index=False)

KeyError: 'Nearest_Place_Index'

In [47]:
restaurants_data

,Restaurant_Name,Locality,Ratings_out_of_5,price,Price Level,Latitude_restaurant,Longitude_restaurant,Name,Latitude_place,Longitude_place,...,park,place_of_worship,point_of_interest,real_estate_agency,shopping_mall,store,synagogue,tourist_attraction,travel_agency,zoo
0,AB's - Absolute Barbecues,Hinjawadi,4.9,700,2,18.592753,73.738215,Blue Ridge Fountain,18.578405,73.737113,...,0,0,1,0,0,0,0,1,0,0
3,I Amsterdam,Hinjawadi,4.3,700,2,18.592753,73.738215,Blue Ridge Fountain,18.578405,73.737113,...,0,0,1,0,0,0,0,1,0,0
7,BeHive,Hinjawadi,4.0,700,2,18.592753,73.738215,Blue Ridge Fountain,18.578405,73.737113,...,0,0,1,0,0,0,0,1,0,0
21,Tarsh Gastronomia,Hinjawadi,4.4,750,2,18.592753,73.738215,Blue Ridge Fountain,18.578405,73.737113,...,0,0,1,0,0,0,0,1,0,0
24,Publiq,Hinjawadi,4.0,800,2,18.592753,73.738215,Blue Ridge Fountain,18.578405,73.737113,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726,Frangipani - Oxford Golf Resort,Lavale,3.6,750,2,18.523023,73.722401,Maangaon Dam,18.564964,73.718103,...,0,0,1,0,0,0,0,1,0,0
2644,The Hungry Hog,Lavale,0.0,125,1,18.523023,73.722401,Maangaon Dam,18.564964,73.718103,...,0,0,1,0,0,0,0,1,0,0
1994,Garva,Mulshi Road,3.4,375,1,18.611846,73.717142,View from YashOne,18.577036,73.719651,...,0,0,1,0,0,0,0,1,0,0
2036,Sambar House,Mulshi Road,0.0,75,1,18.611846,73.717142,View from YashOne,18.577036,73.719651,...,0,0,1,0,0,0,0,1,0,0
2716,Rudra Restaurant & Bar,Mulshi Road,3.1,350,1,18.611846,73.717142,View from YashOne,18.577036,73.719651,...,0,0,1,0,0,0,0,1,0,0

In [13]:
!pip install geopy

Collecting geopy
  Downloading geopy-2.4.0-py3-none-any.whl.metadata (6.8 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
     ---------------------------------------- 0.0/40.3 kB ? eta -:--:--
     ---------------------------------------- 40.3/40.3 kB 2.0 MB/s eta 0:00:00
Downloading geopy-2.4.0-py3-none-any.whl (125 kB)
   ---------------------------------------- 0.0/125.4 kB ? eta -:--:--
   ---------------------------------------- 125.4/125.4 kB 7.2 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.4.0

                  Coordinates  \
0    (18.5640363, 73.7770091)
1    (18.5907879, 73.9268176)
2    (18.5026461, 73.8104869)
3    (18.5524942, 73.9014563)
4    (18.7624486, 73.8832705)
..                        ...
272  (18.5263065, 73.8425036)
273  (18.5220925, 73.9064517)
274  (18.6078112, 73.6997736)
275  (18.4334144, 73.8448499)
276  (18.5230388, 73.8762163)

                                             Area Name
0    Benecare Superspeciality Hospital, Balewadi Hi...
1                     Pune, Maharashtra, 411011, India
2            Kothrud, Pune, Maharashtra, 411038, India
3    Aga Khan Palace, Nagar Road, Kalyani Nagar, Pu...
4       Chakan, Khed, Pune, Maharashtra, 410500, India
..                                                 ...
272  Siddarth Towers, Chaturshringi Road, Shivajina...
273  Bhagwan Tatyasaheb Kawade Marg, Ghorpuri, Pune...
274  Marunji Jhenda Tekdi trail, Mulshi, Pune, Maha...
275  Dhayari, Haveli, Pune, Maharashtra, 411046, India
276  Dr Leena Hiremath, 1st Floor, Sadhu Vaswani Pa...

[277 rows x 2 columns]

In [15]:
result_df.to_csv("result_df.csv")

In [10]:
import pandas as pd
from sklearn.neighbors import NearestNeighbors

# Assuming you have three DataFrames: places_data, restaurants_data, and hotels_data

# Drop unnecessary columns for the matching process
places_features = places_data[['Longitude', 'Latitude']]
restaurants_features = restaurants_data[['Longitude', 'Latitude']]
hotels_features = hotels_data[['Longitude', 'Latitude']]

# Use Nearest Neighbors to find the nearest place for each restaurant
knn_places = NearestNeighbors(n_neighbors=1, metric='haversine')
knn_places.fit(places_features)

# Find the nearest place for each restaurant
distances_restaurants, indices_restaurants = knn_places.kneighbors(restaurants_features)

# Create a new column 'Nearest_Place_Index_Restaurant' to store the index of the nearest place for restaurants
restaurants_data['Nearest_Place_Index'] = indices_restaurants.flatten()

# Merge the 'places_data' DataFrame with 'restaurants_data' based on the 'Nearest_Place_Index_Restaurant'
restaurants_data = pd.merge(restaurants_data, places_data, left_on='Nearest_Place_Index', right_index=True, suffixes=('_restaurant', '_place'))

# Drop unnecessary columns
restaurants_data = restaurants_data.drop(columns=['Nearest_Place_Index'])

# Use Nearest Neighbors to find the nearest place for each hotel
knn_hotels = NearestNeighbors(n_neighbors=1, metric='haversine')
knn_hotels.fit(places_features)

# Find the nearest place for each hotel
distances_hotels, indices_hotels = knn_hotels.kneighbors(hotels_features)

# Create a new column 'Nearest_Place_Index_Hotel' to store the index of the nearest place for hotels
hotels_data['Nearest_Place_Index'] = indices_hotels.flatten()

# Merge the 'places_data' DataFrame with 'hotels_data' based on the 'Nearest_Place_Index_Hotel'
hotels_data = pd.merge(hotels_data, places_data, left_on='Nearest_Place_Index', right_index=True, suffixes=('_hotel', '_place'))

# Drop unnecessary columns
hotels_data = hotels_data.drop(columns=['Nearest_Place_Index'])

# Merge restaurants_data and hotels_data based on the common nearest place
merged_data = pd.merge(restaurants_data, hotels_data, on='Nearest_Place_Index', suffixes=('_restaurant', '_hotel'))

# Drop unnecessary columns
merged_data = merged_data.drop(columns=['Nearest_Place_Index'])

# Now, 'merged_data' contains all the information with restaurants mapped to the closest hotel and both with their nearest places

KeyError: 'Nearest_Place_Index'